{
 "title": "My Dashboard InfluxQL",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heartbeat",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "SELECT count(\"gauge\") FROM \"app.heartbeat\" WHERE $timeFilter GROUP BY time(15s) fill(0)"
    }
   ]
  },
  {
   "title": "CPU & Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU",
     "query": "SELECT mean(\"gauge\") * 100 AS \"CPU\" FROM \"process.cpu.utilization\" WHERE $timeFilter GROUP BY time($__interval)"
    },
    {
     "alias": "Memory",
     "query": "SELECT mean(\"gauge\") / 1048576 AS \"Memory\" FROM \"process.memory.usage\" WHERE $timeFilter GROUP BY time($__interval)"
    }
   ]
  },
  { "title": "Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Current Store Size",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "store.events.by_status.total",
     "query": "SELECT last(\"gauge\") FROM \"store.entries.total\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Store Size by Event Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "status::tag" ], "type": "tag" }
     ],
     "measurement": "store.events.by_status.total",
     "query": "SELECT mean(\"gauge\") FROM \"store.events.by_status.total\" WHERE $timeFilter GROUP BY time($__interval), \"status\"",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "store size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "store.events.by_status.total",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lag",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "store.events.by_status.total",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "status::tag", "operator": "=", "value": "pending" },
      { "condition": "OR", "key": "status::tag", "operator": "=", "value": "failed" }
     ]
    }
   ]
  },
  {
   "title": "Event Throughput",
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 19 },
   "options": {
    "content": "flowchart LR\n    start[/Client/] ==> manager{{Event Manager}}\n    subgraph store [Event Store]\n    manager --> failed[Process Error]\n    manager --> acked[acknowleged]\n    failed -- 42 --> acked\n    end\n    failed ---> dlq[(Dead Letter)]\n    failed -- retry --> failed\n    acked --> finish[\\Exporter\\]"
   },
   "targets": [
    {
     "alias": "manager",
     "measurement": "store.events.by_status.total",
     "query": "SELECT count(\"duration_nano\") FROM \"spans\" WHERE \"span.name\" =~ /\\// AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "status::tag", "operator": "=", "value": "pending" }
     ]
    },
    {
     "alias": "dlq",
     "measurement": "store.events.by_status.total",
     "query": "SELECT count(\"duration_nano\") FROM \"spans\" WHERE \"span.name\" =~ /\\// AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "status::tag", "operator": "=", "value": "dead-letter" }
     ]
    },
    {
     "alias": "failed",
     "measurement": "store.events.by_status.total",
     "query": "SELECT count(\"duration_nano\") FROM \"spans\" WHERE \"span.name\" =~ /\\// AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "status::tag", "operator": "=", "value": "failed" }
     ]
    },
    {
     "alias": "acked",
     "measurement": "store.events.by_status.total",
     "query": "SELECT count(\"duration_nano\") FROM \"spans\" WHERE \"span.name\" =~ /\\// AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "status::tag", "operator": "=", "value": "acked" }
     ]
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 23 },
   "targets": [
    {
     "alias": "retries",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "store.events.retry.total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    }
   ]
  },
  { "title": "REST API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "API Endpoint Performance",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spans",
     "query": "SELECT * FROM \"spans\" WHERE \"span.name\" =~ /\\// AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "API Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "Endpoints",
     "query": "SELECT count(\"duration_nano\") FROM \"spans\" WHERE \"span.name\" =~ /\\// AND $timeFilter GROUP BY time($__interval)"
    }
   ]
  }
 ]
}